### ISSUE TITLE
Unable to compile older couchdb versions

### ISSUE THREAD

**Issue by sahilph** [treehouses/rpi-couchdb#19]
The docker images for CouchDB v2.0.0 and v2.1.0 cannot be build as those versions are not compiling from the Github sources. 
The reason for that is GitHub repo does not have the prebuilt source tarball. (Check this https://github.com/apache/couchdb/issues/1016)

I also downloaded souces for the the latest version (v2.1.1) from the github repo and the one from their official download site ([here](https://dist.apache.org/repos/dist/release/couchdb/source/)) and did a diff of the two folders. There are a lot of important resources missing from github repo. 
 

## Expected Behavior
CouchDB versions 2.1.0 and 2.0.0 should get compiled

## Current Behavior
Getting the error
```
sh(git describe --always --tags) failed with return code 128 and the following output: 
fatal: Not a git repository (or any of the parent directories): .git
```

## Possible Solution
Not sure yet

## Workarounds
Use the pre-existing images on docker hub and stop building these versions on Travis

## Steps to Reproduce (for bugs)
Try to build docker image for v2.1.0, v2.0.0

## Context
Trying to build without kraken and making the docker repo multiarch.
Take a look at branch: https://github.com/treehouses/rpi-couchdb/tree/MA_and_build-without-kraken

## Your Environment
Ubuntu 16.04

**Comment by empeje** [comment]
Is this still valid @sahilph? I'll close this if it's not valid anymore.

**Comment by sahilph** [comment]
Well its still valid. But nothing can be done about this. So It can Be closed.
