### ISSUE TITLE
latest on hub is still 2.2.0 and not 2.3.0

### ISSUE THREAD

**Issue by dogi** [treehouses/rpi-couchdb#39]
https://hub.docker.com/r/treehouses/couchdb/tags

**Comment by jguillod** [comment]
also, current CouchDB version is 2.3.1

**Comment by dogi** [comment]
@jguillod thanks

@lillyxxx can you check if latest version is still 2.2.0 and in that case to put it to 2.3.0

**Comment by lillyxxx** [comment]
@jguillod Just pushed the 2.3.1 version.
@dogi The latest tag in docker is now 2.3.0. 
After testing, we will switch that one also to 2.3.1.

**Comment by chuenniger** [comment]
The problem still isn't solved. It still points to version 2.2.0

plz change the latest tag to the latest version 2.3.1

![Screenshot 2019-11-26 at 22 51 45](https://user-images.githubusercontent.com/188438/69675652-6e06b800-109f-11ea-8fd6-ec29f8c8d472.png)
