### ISSUE TITLE
Support for CouchDB 2.3.1

### ISSUE THREAD

**Issue by UncleSamSwiss** [treehouses/rpi-couchdb#41]
Is there any chance you can add CouchDB 2.3.1 as well or are there issues preventing CouchDB 2.3.1 from compiling on ARM?

**Comment by empeje** [comment]
thanks for the report @UncleSamSwiss , we'll update the rpi-couchdb to version 2.3.1 very soon

**Comment by dogi** [comment]
@empeje we are getting there right now ...

@UncleSamSwiss stay tuned ;)
